# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f08c60350ca370f0c6565035f5f6aeb66026d70775262ed0da303d880e7ac0ca3ad830a4bf622e07ab14b6fd13bb69c15e20ac408ce0ff8f8c23d61f2f45b526
  domain_name: 'http://localhost:3000'

test:
  secret_key_base: 7e787df69b2485155d6b275d967c87be49101adbfc29bad988b31292ef4885022d68032a50d0cb933adbb122ef63bda926a5eae40e58dfe085736318e3357c10
  domain_name: 'http://localhost:3000'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: 'http://filmfans.ulab.com'
