class InsertSizeGuide < ActiveRecord::Migration
  def change
    execute <<-SQL
      INSERT INTO size_guides(category_id, size_name, size_num, country) VALUES
      (1, 'XXS', '0', 'US'),
      (1, 'XXS', '4', 'UK'),
      (1, 'XXS', '36', 'Italy'),
      (1, 'XXS', '32', 'France'),
      (1, 'XXS', '30', 'Denmark'),
      (1, 'XXS', '38', 'Russia'),
      (1, 'XXS', '30', 'Germany'),
      (1, 'XXS', '4', 'Australia'),
      (1, 'XXS', '3', 'Japan'),
      (1, 'XXS - XS', '0', 'US'),
      (1, 'XXS - XS', '6', 'UK'),
      (1, 'XXS - XS', '38', 'Italy'),
      (1, 'XXS - XS', '34', 'France'),
      (1, 'XXS - XS', '32', 'Denmark'),
      (1, 'XXS - XS', '40', 'Russia'),
      (1, 'XXS - XS', '32', 'Germany'),
      (1, 'XXS - XS', '6', 'Australia'),
      (1, 'XXS - XS', '5', 'Japan'),
      (1, 'XS - S', '2 - 4', 'US'),
      (1, 'XS - S', '8', 'UK'),
      (1, 'XS - S', '40', 'Italy'),
      (1, 'XS - S', '36', 'France'),
      (1, 'XS - S', '34', 'Denmark'),
      (1, 'XS - S', '42', 'Russia'),
      (1, 'XS - S', '34', 'Germany'),
      (1, 'XS - S', '8', 'Australia'),
      (1, 'XS - S', '7', 'Japan'),
      (1, 'S - M', '4 - 6', 'US'),
      (1, 'S - M', '10', 'UK'),
      (1, 'S - M', '42', 'Italy'),
      (1, 'S - M', '38', 'France'),
      (1, 'S - M', '36', 'Denmark'),
      (1, 'S - M', '44', 'Russia'),
      (1, 'S - M', '36', 'Germany'),
      (1, 'S - M', '10', 'Australia'),
      (1, 'S - M', '9', 'Japan'),
      (1, 'M - L', '8', 'US'),
      (1, 'M - L', '12', 'UK'),
      (1, 'M - L', '44', 'Italy'),
      (1, 'M - L', '40', 'France'),
      (1, 'M - L', '38', 'Denmark'),
      (1, 'M - L', '46', 'Russia'),
      (1, 'M - L', '38', 'Germany'),
      (1, 'M - L', '12', 'Australia'),
      (1, 'M - L', '11', 'Japan'),
      (1, 'L - XL', '10', 'US'),
      (1, 'L - XL', '14', 'UK'),
      (1, 'L - XL', '46', 'Italy'),
      (1, 'L - XL', '42', 'France'),
      (1, 'L - XL', '40', 'Denmark'),
      (1, 'L - XL', '48', 'Russia'),
      (1, 'L - XL', '40', 'Germany'),
      (1, 'L - XL', '14', 'Australia'),
      (1, 'L - XL', '13', 'Japan'),
      (1, 'XL - XXL', '12', 'US'),
      (1, 'XL - XXL', '16', 'UK'),
      (1, 'XL - XXL', '48', 'Italy'),
      (1, 'XL - XXL', '44', 'France'),
      (1, 'XL - XXL', '42', 'Denmark'),
      (1, 'XL - XXL', '50', 'Russia'),
      (1, 'XL - XXL', '42', 'Germany'),
      (1, 'XL - XXL', '16', 'Australia'),
      (1, 'XL - XXL', '15', 'Japan'),
      (1, 'XXL - XXXL', '14', 'US'),
      (1, 'XXL - XXXL', '18', 'UK'),
      (1, 'XXL - XXXL', '50', 'Italy'),
      (1, 'XXL - XXXL', '46', 'France'),
      (1, 'XXL - XXXL', '44', 'Denmark'),
      (1, 'XXL - XXXL', '52', 'Russia'),
      (1, 'XXL - XXXL', '44', 'Germany'),
      (1, 'XXL - XXXL', '18', 'Australia'),
      (1, 'XXL - XXXL', '17', 'Japan'),
      (2, 'XXS', '0', 'US'),
      (2, 'XXS', '4', 'UK'),
      (2, 'XXS', '36', 'Italy'),
      (2, 'XXS', '32', 'France'),
      (2, 'XXS', '30', 'Denmark'),
      (2, 'XXS', '38', 'Russia'),
      (2, 'XXS', '30', 'Germany'),
      (2, 'XXS', '4', 'Australia'),
      (2, 'XXS', '3', 'Japan'),
      (2, 'XXS - XS', '0', 'US'),
      (2, 'XXS - XS', '6', 'UK'),
      (2, 'XXS - XS', '38', 'Italy'),
      (2, 'XXS - XS', '34', 'France'),
      (2, 'XXS - XS', '32', 'Denmark'),
      (2, 'XXS - XS', '40', 'Russia'),
      (2, 'XXS - XS', '32', 'Germany'),
      (2, 'XXS - XS', '6', 'Australia'),
      (2, 'XXS - XS', '5', 'Japan'),
      (2, 'XS - S', '2 - 4', 'US'),
      (2, 'XS - S', '8', 'UK'),
      (2, 'XS - S', '40', 'Italy'),
      (2, 'XS - S', '36', 'France'),
      (2, 'XS - S', '34', 'Denmark'),
      (2, 'XS - S', '42', 'Russia'),
      (2, 'XS - S', '34', 'Germany'),
      (2, 'XS - S', '8', 'Australia'),
      (2, 'XS - S', '7', 'Japan'),
      (2, 'S - M', '4 - 6', 'US'),
      (2, 'S - M', '10', 'UK'),
      (2, 'S - M', '42', 'Italy'),
      (2, 'S - M', '38', 'France'),
      (2, 'S - M', '36', 'Denmark'),
      (2, 'S - M', '44', 'Russia'),
      (2, 'S - M', '36', 'Germany'),
      (2, 'S - M', '10', 'Australia'),
      (2, 'S - M', '9', 'Japan'),
      (2, 'M - L', '8', 'US'),
      (2, 'M - L', '12', 'UK'),
      (2, 'M - L', '44', 'Italy'),
      (2, 'M - L', '40', 'France'),
      (2, 'M - L', '38', 'Denmark'),
      (2, 'M - L', '46', 'Russia'),
      (2, 'M - L', '38', 'Germany'),
      (2, 'M - L', '12', 'Australia'),
      (2, 'M - L', '11', 'Japan'),
      (2, 'L - XL', '10', 'US'),
      (2, 'L - XL', '14', 'UK'),
      (2, 'L - XL', '46', 'Italy'),
      (2, 'L - XL', '42', 'France'),
      (2, 'L - XL', '40', 'Denmark'),
      (2, 'L - XL', '48', 'Russia'),
      (2, 'L - XL', '40', 'Germany'),
      (2, 'L - XL', '14', 'Australia'),
      (2, 'L - XL', '13', 'Japan'),
      (2, 'XL - XXL', '12', 'US'),
      (2, 'XL - XXL', '16', 'UK'),
      (2, 'XL - XXL', '48', 'Italy'),
      (2, 'XL - XXL', '44', 'France'),
      (2, 'XL - XXL', '42', 'Denmark'),
      (2, 'XL - XXL', '50', 'Russia'),
      (2, 'XL - XXL', '42', 'Germany'),
      (2, 'XL - XXL', '16', 'Australia'),
      (2, 'XL - XXL', '15', 'Japan'),
      (2, 'XXL - XXXL', '14', 'US'),
      (2, 'XXL - XXXL', '18', 'UK'),
      (2, 'XXL - XXXL', '50', 'Italy'),
      (2, 'XXL - XXXL', '46', 'France'),
      (2, 'XXL - XXXL', '44', 'Denmark'),
      (2, 'XXL - XXXL', '52', 'Russia'),
      (2, 'XXL - XXXL', '44', 'Germany'),
      (2, 'XXL - XXXL', '18', 'Australia'),
      (2, 'XXL - XXXL', '17', 'Japan'),
      (3, 'XXS', '0', 'US'),
      (3, 'XXS', '4', 'UK'),
      (3, 'XXS', '36', 'Italy'),
      (3, 'XXS', '32', 'France'),
      (3, 'XXS', '30', 'Denmark'),
      (3, 'XXS', '38', 'Russia'),
      (3, 'XXS', '30', 'Germany'),
      (3, 'XXS', '4', 'Australia'),
      (3, 'XXS', '3', 'Japan'),
      (3, 'XXS - XS', '0', 'US'),
      (3, 'XXS - XS', '6', 'UK'),
      (3, 'XXS - XS', '38', 'Italy'),
      (3, 'XXS - XS', '34', 'France'),
      (3, 'XXS - XS', '32', 'Denmark'),
      (3, 'XXS - XS', '40', 'Russia'),
      (3, 'XXS - XS', '32', 'Germany'),
      (3, 'XXS - XS', '6', 'Australia'),
      (3, 'XXS - XS', '5', 'Japan'),
      (3, 'XS - S', '2 - 4', 'US'),
      (3, 'XS - S', '8', 'UK'),
      (3, 'XS - S', '40', 'Italy'),
      (3, 'XS - S', '36', 'France'),
      (3, 'XS - S', '34', 'Denmark'),
      (3, 'XS - S', '42', 'Russia'),
      (3, 'XS - S', '34', 'Germany'),
      (3, 'XS - S', '8', 'Australia'),
      (3, 'XS - S', '7', 'Japan'),
      (3, 'S - M', '4 - 6', 'US'),
      (3, 'S - M', '10', 'UK'),
      (3, 'S - M', '42', 'Italy'),
      (3, 'S - M', '38', 'France'),
      (3, 'S - M', '36', 'Denmark'),
      (3, 'S - M', '44', 'Russia'),
      (3, 'S - M', '36', 'Germany'),
      (3, 'S - M', '10', 'Australia'),
      (3, 'S - M', '9', 'Japan'),
      (3, 'M - L', '8', 'US'),
      (3, 'M - L', '12', 'UK'),
      (3, 'M - L', '44', 'Italy'),
      (3, 'M - L', '40', 'France'),
      (3, 'M - L', '38', 'Denmark'),
      (3, 'M - L', '46', 'Russia'),
      (3, 'M - L', '38', 'Germany'),
      (3, 'M - L', '12', 'Australia'),
      (3, 'M - L', '11', 'Japan'),
      (3, 'L - XL', '10', 'US'),
      (3, 'L - XL', '14', 'UK'),
      (3, 'L - XL', '46', 'Italy'),
      (3, 'L - XL', '42', 'France'),
      (3, 'L - XL', '40', 'Denmark'),
      (3, 'L - XL', '48', 'Russia'),
      (3, 'L - XL', '40', 'Germany'),
      (3, 'L - XL', '14', 'Australia'),
      (3, 'L - XL', '13', 'Japan'),
      (3, 'XL - XXL', '12', 'US'),
      (3, 'XL - XXL', '16', 'UK'),
      (3, 'XL - XXL', '48', 'Italy'),
      (3, 'XL - XXL', '44', 'France'),
      (3, 'XL - XXL', '42', 'Denmark'),
      (3, 'XL - XXL', '50', 'Russia'),
      (3, 'XL - XXL', '42', 'Germany'),
      (3, 'XL - XXL', '16', 'Australia'),
      (3, 'XL - XXL', '15', 'Japan'),
      (3, 'XXL - XXXL', '14', 'US'),
      (3, 'XXL - XXXL', '18', 'UK'),
      (3, 'XXL - XXXL', '50', 'Italy'),
      (3, 'XXL - XXXL', '46', 'France'),
      (3, 'XXL - XXXL', '44', 'Denmark'),
      (3, 'XXL - XXXL', '52', 'Russia'),
      (3, 'XXL - XXXL', '44', 'Germany'),
      (3, 'XXL - XXXL', '18', 'Australia'),
      (3, 'XXL - XXXL', '17', 'Japan'),
      (4, 'XXS', '0', 'US'),
      (4, 'XXS', '4', 'UK'),
      (4, 'XXS', '36', 'Italy'),
      (4, 'XXS', '32', 'France'),
      (4, 'XXS', '30', 'Denmark'),
      (4, 'XXS', '38', 'Russia'),
      (4, 'XXS', '30', 'Germany'),
      (4, 'XXS', '4', 'Australia'),
      (4, 'XXS', '3', 'Japan'),
      (4, 'XXS - XS', '0', 'US'),
      (4, 'XXS - XS', '6', 'UK'),
      (4, 'XXS - XS', '38', 'Italy'),
      (4, 'XXS - XS', '34', 'France'),
      (4, 'XXS - XS', '32', 'Denmark'),
      (4, 'XXS - XS', '40', 'Russia'),
      (4, 'XXS - XS', '32', 'Germany'),
      (4, 'XXS - XS', '6', 'Australia'),
      (4, 'XXS - XS', '5', 'Japan'),
      (4, 'XS - S', '2 - 4', 'US'),
      (4, 'XS - S', '8', 'UK'),
      (4, 'XS - S', '40', 'Italy'),
      (4, 'XS - S', '36', 'France'),
      (4, 'XS - S', '34', 'Denmark'),
      (4, 'XS - S', '42', 'Russia'),
      (4, 'XS - S', '34', 'Germany'),
      (4, 'XS - S', '8', 'Australia'),
      (4, 'XS - S', '7', 'Japan'),
      (4, 'S - M', '4 - 6', 'US'),
      (4, 'S - M', '10', 'UK'),
      (4, 'S - M', '42', 'Italy'),
      (4, 'S - M', '38', 'France'),
      (4, 'S - M', '36', 'Denmark'),
      (4, 'S - M', '44', 'Russia'),
      (4, 'S - M', '36', 'Germany'),
      (4, 'S - M', '10', 'Australia'),
      (4, 'S - M', '9', 'Japan'),
      (4, 'M - L', '8', 'US'),
      (4, 'M - L', '12', 'UK'),
      (4, 'M - L', '44', 'Italy'),
      (4, 'M - L', '40', 'France'),
      (4, 'M - L', '38', 'Denmark'),
      (4, 'M - L', '46', 'Russia'),
      (4, 'M - L', '38', 'Germany'),
      (4, 'M - L', '12', 'Australia'),
      (4, 'M - L', '11', 'Japan'),
      (4, 'L - XL', '10', 'US'),
      (4, 'L - XL', '14', 'UK'),
      (4, 'L - XL', '46', 'Italy'),
      (4, 'L - XL', '42', 'France'),
      (4, 'L - XL', '40', 'Denmark'),
      (4, 'L - XL', '48', 'Russia'),
      (4, 'L - XL', '40', 'Germany'),
      (4, 'L - XL', '14', 'Australia'),
      (4, 'L - XL', '13', 'Japan'),
      (4, 'XL - XXL', '12', 'US'),
      (4, 'XL - XXL', '16', 'UK'),
      (4, 'XL - XXL', '48', 'Italy'),
      (4, 'XL - XXL', '44', 'France'),
      (4, 'XL - XXL', '42', 'Denmark'),
      (4, 'XL - XXL', '50', 'Russia'),
      (4, 'XL - XXL', '42', 'Germany'),
      (4, 'XL - XXL', '16', 'Australia'),
      (4, 'XL - XXL', '15', 'Japan'),
      (4, 'XXL - XXXL', '14', 'US'),
      (4, 'XXL - XXXL', '18', 'UK'),
      (4, 'XXL - XXXL', '50', 'Italy'),
      (4, 'XXL - XXXL', '46', 'France'),
      (4, 'XXL - XXXL', '44', 'Denmark'),
      (4, 'XXL - XXXL', '52', 'Russia'),
      (4, 'XXL - XXXL', '44', 'Germany'),
      (4, 'XXL - XXXL', '18', 'Australia'),
      (4, 'XXL - XXXL', '17', 'Japan'),
      (6, 'XXS', '0', 'US'),
      (6, 'XXS', '4', 'UK'),
      (6, 'XXS', '36', 'Italy'),
      (6, 'XXS', '32', 'France'),
      (6, 'XXS', '30', 'Denmark'),
      (6, 'XXS', '38', 'Russia'),
      (6, 'XXS', '30', 'Germany'),
      (6, 'XXS', '4', 'Australia'),
      (6, 'XXS', '3', 'Japan'),
      (6, 'XXS - XS', '0', 'US'),
      (6, 'XXS - XS', '6', 'UK'),
      (6, 'XXS - XS', '38', 'Italy'),
      (6, 'XXS - XS', '34', 'France'),
      (6, 'XXS - XS', '32', 'Denmark'),
      (6, 'XXS - XS', '40', 'Russia'),
      (6, 'XXS - XS', '32', 'Germany'),
      (6, 'XXS - XS', '6', 'Australia'),
      (6, 'XXS - XS', '5', 'Japan'),
      (6, 'XS - S', '2 - 4', 'US'),
      (6, 'XS - S', '8', 'UK'),
      (6, 'XS - S', '40', 'Italy'),
      (6, 'XS - S', '36', 'France'),
      (6, 'XS - S', '34', 'Denmark'),
      (6, 'XS - S', '42', 'Russia'),
      (6, 'XS - S', '34', 'Germany'),
      (6, 'XS - S', '8', 'Australia'),
      (6, 'XS - S', '7', 'Japan'),
      (6, 'S - M', '4 - 6', 'US'),
      (6, 'S - M', '10', 'UK'),
      (6, 'S - M', '42', 'Italy'),
      (6, 'S - M', '38', 'France'),
      (6, 'S - M', '36', 'Denmark'),
      (6, 'S - M', '44', 'Russia'),
      (6, 'S - M', '36', 'Germany'),
      (6, 'S - M', '10', 'Australia'),
      (6, 'S - M', '9', 'Japan'),
      (6, 'M - L', '8', 'US'),
      (6, 'M - L', '12', 'UK'),
      (6, 'M - L', '44', 'Italy'),
      (6, 'M - L', '40', 'France'),
      (6, 'M - L', '38', 'Denmark'),
      (6, 'M - L', '46', 'Russia'),
      (6, 'M - L', '38', 'Germany'),
      (6, 'M - L', '12', 'Australia'),
      (6, 'M - L', '11', 'Japan'),
      (6, 'L - XL', '10', 'US'),
      (6, 'L - XL', '14', 'UK'),
      (6, 'L - XL', '46', 'Italy'),
      (6, 'L - XL', '42', 'France'),
      (6, 'L - XL', '40', 'Denmark'),
      (6, 'L - XL', '48', 'Russia'),
      (6, 'L - XL', '40', 'Germany'),
      (6, 'L - XL', '14', 'Australia'),
      (6, 'L - XL', '13', 'Japan'),
      (6, 'XL - XXL', '12', 'US'),
      (6, 'XL - XXL', '16', 'UK'),
      (6, 'XL - XXL', '48', 'Italy'),
      (6, 'XL - XXL', '44', 'France'),
      (6, 'XL - XXL', '42', 'Denmark'),
      (6, 'XL - XXL', '50', 'Russia'),
      (6, 'XL - XXL', '42', 'Germany'),
      (6, 'XL - XXL', '16', 'Australia'),
      (6, 'XL - XXL', '15', 'Japan'),
      (6, 'XXL - XXXL', '14', 'US'),
      (6, 'XXL - XXXL', '18', 'UK'),
      (6, 'XXL - XXXL', '50', 'Italy'),
      (6, 'XXL - XXXL', '46', 'France'),
      (6, 'XXL - XXXL', '44', 'Denmark'),
      (6, 'XXL - XXXL', '52', 'Russia'),
      (6, 'XXL - XXXL', '44', 'Germany'),
      (6, 'XXL - XXXL', '18', 'Australia'),
      (6, 'XXL - XXXL', '17', 'Japan'),
      (7, 'XXS', '0', 'US'),
      (7, 'XXS', '4', 'UK'),
      (7, 'XXS', '36', 'Italy'),
      (7, 'XXS', '32', 'France'),
      (7, 'XXS', '30', 'Denmark'),
      (7, 'XXS', '38', 'Russia'),
      (7, 'XXS', '30', 'Germany'),
      (7, 'XXS', '4', 'Australia'),
      (7, 'XXS', '3', 'Japan'),
      (7, 'XXS - XS', '0', 'US'),
      (7, 'XXS - XS', '6', 'UK'),
      (7, 'XXS - XS', '38', 'Italy'),
      (7, 'XXS - XS', '34', 'France'),
      (7, 'XXS - XS', '32', 'Denmark'),
      (7, 'XXS - XS', '40', 'Russia'),
      (7, 'XXS - XS', '32', 'Germany'),
      (7, 'XXS - XS', '6', 'Australia'),
      (7, 'XXS - XS', '5', 'Japan'),
      (7, 'XS - S', '2 - 4', 'US'),
      (7, 'XS - S', '8', 'UK'),
      (7, 'XS - S', '40', 'Italy'),
      (7, 'XS - S', '36', 'France'),
      (7, 'XS - S', '34', 'Denmark'),
      (7, 'XS - S', '42', 'Russia'),
      (7, 'XS - S', '34', 'Germany'),
      (7, 'XS - S', '8', 'Australia'),
      (7, 'XS - S', '7', 'Japan'),
      (7, 'S - M', '4 - 6', 'US'),
      (7, 'S - M', '10', 'UK'),
      (7, 'S - M', '42', 'Italy'),
      (7, 'S - M', '38', 'France'),
      (7, 'S - M', '36', 'Denmark'),
      (7, 'S - M', '44', 'Russia'),
      (7, 'S - M', '36', 'Germany'),
      (7, 'S - M', '10', 'Australia'),
      (7, 'S - M', '9', 'Japan'),
      (7, 'M - L', '8', 'US'),
      (7, 'M - L', '12', 'UK'),
      (7, 'M - L', '44', 'Italy'),
      (7, 'M - L', '40', 'France'),
      (7, 'M - L', '38', 'Denmark'),
      (7, 'M - L', '46', 'Russia'),
      (7, 'M - L', '38', 'Germany'),
      (7, 'M - L', '12', 'Australia'),
      (7, 'M - L', '11', 'Japan'),
      (7, 'L - XL', '10', 'US'),
      (7, 'L - XL', '14', 'UK'),
      (7, 'L - XL', '46', 'Italy'),
      (7, 'L - XL', '42', 'France'),
      (7, 'L - XL', '40', 'Denmark'),
      (7, 'L - XL', '48', 'Russia'),
      (7, 'L - XL', '40', 'Germany'),
      (7, 'L - XL', '14', 'Australia'),
      (7, 'L - XL', '13', 'Japan'),
      (7, 'XL - XXL', '12', 'US'),
      (7, 'XL - XXL', '16', 'UK'),
      (7, 'XL - XXL', '48', 'Italy'),
      (7, 'XL - XXL', '44', 'France'),
      (7, 'XL - XXL', '42', 'Denmark'),
      (7, 'XL - XXL', '50', 'Russia'),
      (7, 'XL - XXL', '42', 'Germany'),
      (7, 'XL - XXL', '16', 'Australia'),
      (7, 'XL - XXL', '15', 'Japan'),
      (7, 'XXL - XXXL', '14', 'US'),
      (7, 'XXL - XXXL', '18', 'UK'),
      (7, 'XXL - XXXL', '50', 'Italy'),
      (7, 'XXL - XXXL', '46', 'France'),
      (7, 'XXL - XXXL', '44', 'Denmark'),
      (7, 'XXL - XXXL', '52', 'Russia'),
      (7, 'XXL - XXXL', '44', 'Germany'),
      (7, 'XXL - XXXL', '18', 'Australia'),
      (7, 'XXL - XXXL', '17', 'Japan'),
      (8, 'XXS', '0', 'US'),
      (8, 'XXS', '4', 'UK'),
      (8, 'XXS', '36', 'Italy'),
      (8, 'XXS', '32', 'France'),
      (8, 'XXS', '30', 'Denmark'),
      (8, 'XXS', '38', 'Russia'),
      (8, 'XXS', '30', 'Germany'),
      (8, 'XXS', '4', 'Australia'),
      (8, 'XXS', '3', 'Japan'),
      (8, 'XXS - XS', '0', 'US'),
      (8, 'XXS - XS', '6', 'UK'),
      (8, 'XXS - XS', '38', 'Italy'),
      (8, 'XXS - XS', '34', 'France'),
      (8, 'XXS - XS', '32', 'Denmark'),
      (8, 'XXS - XS', '40', 'Russia'),
      (8, 'XXS - XS', '32', 'Germany'),
      (8, 'XXS - XS', '6', 'Australia'),
      (8, 'XXS - XS', '5', 'Japan'),
      (8, 'XS - S', '2 - 4', 'US'),
      (8, 'XS - S', '8', 'UK'),
      (8, 'XS - S', '40', 'Italy'),
      (8, 'XS - S', '36', 'France'),
      (8, 'XS - S', '34', 'Denmark'),
      (8, 'XS - S', '42', 'Russia'),
      (8, 'XS - S', '34', 'Germany'),
      (8, 'XS - S', '8', 'Australia'),
      (8, 'XS - S', '7', 'Japan'),
      (8, 'S - M', '4 - 6', 'US'),
      (8, 'S - M', '10', 'UK'),
      (8, 'S - M', '42', 'Italy'),
      (8, 'S - M', '38', 'France'),
      (8, 'S - M', '36', 'Denmark'),
      (8, 'S - M', '44', 'Russia'),
      (8, 'S - M', '36', 'Germany'),
      (8, 'S - M', '10', 'Australia'),
      (8, 'S - M', '9', 'Japan'),
      (8, 'M - L', '8', 'US'),
      (8, 'M - L', '12', 'UK'),
      (8, 'M - L', '44', 'Italy'),
      (8, 'M - L', '40', 'France'),
      (8, 'M - L', '38', 'Denmark'),
      (8, 'M - L', '46', 'Russia'),
      (8, 'M - L', '38', 'Germany'),
      (8, 'M - L', '12', 'Australia'),
      (8, 'M - L', '11', 'Japan'),
      (8, 'L - XL', '10', 'US'),
      (8, 'L - XL', '14', 'UK'),
      (8, 'L - XL', '46', 'Italy'),
      (8, 'L - XL', '42', 'France'),
      (8, 'L - XL', '40', 'Denmark'),
      (8, 'L - XL', '48', 'Russia'),
      (8, 'L - XL', '40', 'Germany'),
      (8, 'L - XL', '14', 'Australia'),
      (8, 'L - XL', '13', 'Japan'),
      (8, 'XL - XXL', '12', 'US'),
      (8, 'XL - XXL', '16', 'UK'),
      (8, 'XL - XXL', '48', 'Italy'),
      (8, 'XL - XXL', '44', 'France'),
      (8, 'XL - XXL', '42', 'Denmark'),
      (8, 'XL - XXL', '50', 'Russia'),
      (8, 'XL - XXL', '42', 'Germany'),
      (8, 'XL - XXL', '16', 'Australia'),
      (8, 'XL - XXL', '15', 'Japan'),
      (8, 'XXL - XXXL', '14', 'US'),
      (8, 'XXL - XXXL', '18', 'UK'),
      (8, 'XXL - XXXL', '50', 'Italy'),
      (8, 'XXL - XXXL', '46', 'France'),
      (8, 'XXL - XXXL', '44', 'Denmark'),
      (8, 'XXL - XXXL', '52', 'Russia'),
      (8, 'XXL - XXXL', '44', 'Germany'),
      (8, 'XXL - XXXL', '18', 'Australia'),
      (8, 'XXL - XXXL', '17', 'Japan'),
      (9, 'XXS', '0', 'US'),
      (9, 'XXS', '4', 'UK'),
      (9, 'XXS', '36', 'Italy'),
      (9, 'XXS', '32', 'France'),
      (9, 'XXS', '30', 'Denmark'),
      (9, 'XXS', '38', 'Russia'),
      (9, 'XXS', '30', 'Germany'),
      (9, 'XXS', '4', 'Australia'),
      (9, 'XXS', '3', 'Japan'),
      (9, 'XXS - XS', '0', 'US'),
      (9, 'XXS - XS', '6', 'UK'),
      (9, 'XXS - XS', '38', 'Italy'),
      (9, 'XXS - XS', '34', 'France'),
      (9, 'XXS - XS', '32', 'Denmark'),
      (9, 'XXS - XS', '40', 'Russia'),
      (9, 'XXS - XS', '32', 'Germany'),
      (9, 'XXS - XS', '6', 'Australia'),
      (9, 'XXS - XS', '5', 'Japan'),
      (9, 'XS - S', '2 - 4', 'US'),
      (9, 'XS - S', '8', 'UK'),
      (9, 'XS - S', '40', 'Italy'),
      (9, 'XS - S', '36', 'France'),
      (9, 'XS - S', '34', 'Denmark'),
      (9, 'XS - S', '42', 'Russia'),
      (9, 'XS - S', '34', 'Germany'),
      (9, 'XS - S', '8', 'Australia'),
      (9, 'XS - S', '7', 'Japan'),
      (9, 'S - M', '4 - 6', 'US'),
      (9, 'S - M', '10', 'UK'),
      (9, 'S - M', '42', 'Italy'),
      (9, 'S - M', '38', 'France'),
      (9, 'S - M', '36', 'Denmark'),
      (9, 'S - M', '44', 'Russia'),
      (9, 'S - M', '36', 'Germany'),
      (9, 'S - M', '10', 'Australia'),
      (9, 'S - M', '9', 'Japan'),
      (9, 'M - L', '8', 'US'),
      (9, 'M - L', '12', 'UK'),
      (9, 'M - L', '44', 'Italy'),
      (9, 'M - L', '40', 'France'),
      (9, 'M - L', '38', 'Denmark'),
      (9, 'M - L', '46', 'Russia'),
      (9, 'M - L', '38', 'Germany'),
      (9, 'M - L', '12', 'Australia'),
      (9, 'M - L', '11', 'Japan'),
      (9, 'L - XL', '10', 'US'),
      (9, 'L - XL', '14', 'UK'),
      (9, 'L - XL', '46', 'Italy'),
      (9, 'L - XL', '42', 'France'),
      (9, 'L - XL', '40', 'Denmark'),
      (9, 'L - XL', '48', 'Russia'),
      (9, 'L - XL', '40', 'Germany'),
      (9, 'L - XL', '14', 'Australia'),
      (9, 'L - XL', '13', 'Japan'),
      (9, 'XL - XXL', '12', 'US'),
      (9, 'XL - XXL', '16', 'UK'),
      (9, 'XL - XXL', '48', 'Italy'),
      (9, 'XL - XXL', '44', 'France'),
      (9, 'XL - XXL', '42', 'Denmark'),
      (9, 'XL - XXL', '50', 'Russia'),
      (9, 'XL - XXL', '42', 'Germany'),
      (9, 'XL - XXL', '16', 'Australia'),
      (9, 'XL - XXL', '15', 'Japan'),
      (9, 'XXL - XXXL', '14', 'US'),
      (9, 'XXL - XXXL', '18', 'UK'),
      (9, 'XXL - XXXL', '50', 'Italy'),
      (9, 'XXL - XXXL', '46', 'France'),
      (9, 'XXL - XXXL', '44', 'Denmark'),
      (9, 'XXL - XXXL', '52', 'Russia'),
      (9, 'XXL - XXXL', '44', 'Germany'),
      (9, 'XXL - XXXL', '18', 'Australia'),
      (9, 'XXL - XXXL', '17', 'Japan'),
      (10, 'XXS', '0', 'US'),
      (10, 'XXS', '4', 'UK'),
      (10, 'XXS', '36', 'Italy'),
      (10, 'XXS', '32', 'France'),
      (10, 'XXS', '30', 'Denmark'),
      (10, 'XXS', '38', 'Russia'),
      (10, 'XXS', '30', 'Germany'),
      (10, 'XXS', '4', 'Australia'),
      (10, 'XXS', '3', 'Japan'),
      (10, 'XXS - XS', '0', 'US'),
      (10, 'XXS - XS', '6', 'UK'),
      (10, 'XXS - XS', '38', 'Italy'),
      (10, 'XXS - XS', '34', 'France'),
      (10, 'XXS - XS', '32', 'Denmark'),
      (10, 'XXS - XS', '40', 'Russia'),
      (10, 'XXS - XS', '32', 'Germany'),
      (10, 'XXS - XS', '6', 'Australia'),
      (10, 'XXS - XS', '5', 'Japan'),
      (10, 'XS - S', '2 - 4', 'US'),
      (10, 'XS - S', '8', 'UK'),
      (10, 'XS - S', '40', 'Italy'),
      (10, 'XS - S', '36', 'France'),
      (10, 'XS - S', '34', 'Denmark'),
      (10, 'XS - S', '42', 'Russia'),
      (10, 'XS - S', '34', 'Germany'),
      (10, 'XS - S', '8', 'Australia'),
      (10, 'XS - S', '7', 'Japan'),
      (10, 'S - M', '4 - 6', 'US'),
      (10, 'S - M', '10', 'UK'),
      (10, 'S - M', '42', 'Italy'),
      (10, 'S - M', '38', 'France'),
      (10, 'S - M', '36', 'Denmark'),
      (10, 'S - M', '44', 'Russia'),
      (10, 'S - M', '36', 'Germany'),
      (10, 'S - M', '10', 'Australia'),
      (10, 'S - M', '9', 'Japan'),
      (10, 'M - L', '8', 'US'),
      (10, 'M - L', '12', 'UK'),
      (10, 'M - L', '44', 'Italy'),
      (10, 'M - L', '40', 'France'),
      (10, 'M - L', '38', 'Denmark'),
      (10, 'M - L', '46', 'Russia'),
      (10, 'M - L', '38', 'Germany'),
      (10, 'M - L', '12', 'Australia'),
      (10, 'M - L', '11', 'Japan'),
      (10, 'L - XL', '10', 'US'),
      (10, 'L - XL', '14', 'UK'),
      (10, 'L - XL', '46', 'Italy'),
      (10, 'L - XL', '42', 'France'),
      (10, 'L - XL', '40', 'Denmark'),
      (10, 'L - XL', '48', 'Russia'),
      (10, 'L - XL', '40', 'Germany'),
      (10, 'L - XL', '14', 'Australia'),
      (10, 'L - XL', '13', 'Japan'),
      (10, 'XL - XXL', '12', 'US'),
      (10, 'XL - XXL', '16', 'UK'),
      (10, 'XL - XXL', '48', 'Italy'),
      (10, 'XL - XXL', '44', 'France'),
      (10, 'XL - XXL', '42', 'Denmark'),
      (10, 'XL - XXL', '50', 'Russia'),
      (10, 'XL - XXL', '42', 'Germany'),
      (10, 'XL - XXL', '16', 'Australia'),
      (10, 'XL - XXL', '15', 'Japan'),
      (10, 'XXL - XXXL', '14', 'US'),
      (10, 'XXL - XXXL', '18', 'UK'),
      (10, 'XXL - XXXL', '50', 'Italy'),
      (10, 'XXL - XXXL', '46', 'France'),
      (10, 'XXL - XXXL', '44', 'Denmark'),
      (10, 'XXL - XXXL', '52', 'Russia'),
      (10, 'XXL - XXXL', '44', 'Germany'),
      (10, 'XXL - XXXL', '18', 'Australia'),
      (10, 'XXL - XXXL', '17', 'Japan'),
      (11, 'XXS', '0', 'US'),
      (11, 'XXS', '4', 'UK'),
      (11, 'XXS', '36', 'Italy'),
      (11, 'XXS', '32', 'France'),
      (11, 'XXS', '30', 'Denmark'),
      (11, 'XXS', '38', 'Russia'),
      (11, 'XXS', '30', 'Germany'),
      (11, 'XXS', '4', 'Australia'),
      (11, 'XXS', '3', 'Japan'),
      (11, 'XXS - XS', '0', 'US'),
      (11, 'XXS - XS', '6', 'UK'),
      (11, 'XXS - XS', '38', 'Italy'),
      (11, 'XXS - XS', '34', 'France'),
      (11, 'XXS - XS', '32', 'Denmark'),
      (11, 'XXS - XS', '40', 'Russia'),
      (11, 'XXS - XS', '32', 'Germany'),
      (11, 'XXS - XS', '6', 'Australia'),
      (11, 'XXS - XS', '5', 'Japan'),
      (11, 'XS - S', '2 - 4', 'US'),
      (11, 'XS - S', '8', 'UK'),
      (11, 'XS - S', '40', 'Italy'),
      (11, 'XS - S', '36', 'France'),
      (11, 'XS - S', '34', 'Denmark'),
      (11, 'XS - S', '42', 'Russia'),
      (11, 'XS - S', '34', 'Germany'),
      (11, 'XS - S', '8', 'Australia'),
      (11, 'XS - S', '7', 'Japan'),
      (11, 'S - M', '4 - 6', 'US'),
      (11, 'S - M', '10', 'UK'),
      (11, 'S - M', '42', 'Italy'),
      (11, 'S - M', '38', 'France'),
      (11, 'S - M', '36', 'Denmark'),
      (11, 'S - M', '44', 'Russia'),
      (11, 'S - M', '36', 'Germany'),
      (11, 'S - M', '10', 'Australia'),
      (11, 'S - M', '9', 'Japan'),
      (11, 'M - L', '8', 'US'),
      (11, 'M - L', '12', 'UK'),
      (11, 'M - L', '44', 'Italy'),
      (11, 'M - L', '40', 'France'),
      (11, 'M - L', '38', 'Denmark'),
      (11, 'M - L', '46', 'Russia'),
      (11, 'M - L', '38', 'Germany'),
      (11, 'M - L', '12', 'Australia'),
      (11, 'M - L', '11', 'Japan'),
      (11, 'L - XL', '10', 'US'),
      (11, 'L - XL', '14', 'UK'),
      (11, 'L - XL', '46', 'Italy'),
      (11, 'L - XL', '42', 'France'),
      (11, 'L - XL', '40', 'Denmark'),
      (11, 'L - XL', '48', 'Russia'),
      (11, 'L - XL', '40', 'Germany'),
      (11, 'L - XL', '14', 'Australia'),
      (11, 'L - XL', '13', 'Japan'),
      (11, 'XL - XXL', '12', 'US'),
      (11, 'XL - XXL', '16', 'UK'),
      (11, 'XL - XXL', '48', 'Italy'),
      (11, 'XL - XXL', '44', 'France'),
      (11, 'XL - XXL', '42', 'Denmark'),
      (11, 'XL - XXL', '50', 'Russia'),
      (11, 'XL - XXL', '42', 'Germany'),
      (11, 'XL - XXL', '16', 'Australia'),
      (11, 'XL - XXL', '15', 'Japan'),
      (11, 'XXL - XXXL', '14', 'US'),
      (11, 'XXL - XXXL', '18', 'UK'),
      (11, 'XXL - XXXL', '50', 'Italy'),
      (11, 'XXL - XXXL', '46', 'France'),
      (11, 'XXL - XXXL', '44', 'Denmark'),
      (11, 'XXL - XXXL', '52', 'Russia'),
      (11, 'XXL - XXXL', '44', 'Germany'),
      (11, 'XXL - XXXL', '18', 'Australia'),
      (11, 'XXL - XXXL', '17', 'Japan'),
      (12, 'XXS', '0', 'US'),
      (12, 'XXS', '4', 'UK'),
      (12, 'XXS', '36', 'Italy'),
      (12, 'XXS', '32', 'France'),
      (12, 'XXS', '30', 'Denmark'),
      (12, 'XXS', '38', 'Russia'),
      (12, 'XXS', '30', 'Germany'),
      (12, 'XXS', '4', 'Australia'),
      (12, 'XXS', '3', 'Japan'),
      (12, 'XXS - XS', '0', 'US'),
      (12, 'XXS - XS', '6', 'UK'),
      (12, 'XXS - XS', '38', 'Italy'),
      (12, 'XXS - XS', '34', 'France'),
      (12, 'XXS - XS', '32', 'Denmark'),
      (12, 'XXS - XS', '40', 'Russia'),
      (12, 'XXS - XS', '32', 'Germany'),
      (12, 'XXS - XS', '6', 'Australia'),
      (12, 'XXS - XS', '5', 'Japan'),
      (12, 'XS - S', '2 - 4', 'US'),
      (12, 'XS - S', '8', 'UK'),
      (12, 'XS - S', '40', 'Italy'),
      (12, 'XS - S', '36', 'France'),
      (12, 'XS - S', '34', 'Denmark'),
      (12, 'XS - S', '42', 'Russia'),
      (12, 'XS - S', '34', 'Germany'),
      (12, 'XS - S', '8', 'Australia'),
      (12, 'XS - S', '7', 'Japan'),
      (12, 'S - M', '4 - 6', 'US'),
      (12, 'S - M', '10', 'UK'),
      (12, 'S - M', '42', 'Italy'),
      (12, 'S - M', '38', 'France'),
      (12, 'S - M', '36', 'Denmark'),
      (12, 'S - M', '44', 'Russia'),
      (12, 'S - M', '36', 'Germany'),
      (12, 'S - M', '10', 'Australia'),
      (12, 'S - M', '9', 'Japan'),
      (12, 'M - L', '8', 'US'),
      (12, 'M - L', '12', 'UK'),
      (12, 'M - L', '44', 'Italy'),
      (12, 'M - L', '40', 'France'),
      (12, 'M - L', '38', 'Denmark'),
      (12, 'M - L', '46', 'Russia'),
      (12, 'M - L', '38', 'Germany'),
      (12, 'M - L', '12', 'Australia'),
      (12, 'M - L', '11', 'Japan'),
      (12, 'L - XL', '10', 'US'),
      (12, 'L - XL', '14', 'UK'),
      (12, 'L - XL', '46', 'Italy'),
      (12, 'L - XL', '42', 'France'),
      (12, 'L - XL', '40', 'Denmark'),
      (12, 'L - XL', '48', 'Russia'),
      (12, 'L - XL', '40', 'Germany'),
      (12, 'L - XL', '14', 'Australia'),
      (12, 'L - XL', '13', 'Japan'),
      (12, 'XL - XXL', '12', 'US'),
      (12, 'XL - XXL', '16', 'UK'),
      (12, 'XL - XXL', '48', 'Italy'),
      (12, 'XL - XXL', '44', 'France'),
      (12, 'XL - XXL', '42', 'Denmark'),
      (12, 'XL - XXL', '50', 'Russia'),
      (12, 'XL - XXL', '42', 'Germany'),
      (12, 'XL - XXL', '16', 'Australia'),
      (12, 'XL - XXL', '15', 'Japan'),
      (12, 'XXL - XXXL', '14', 'US'),
      (12, 'XXL - XXXL', '18', 'UK'),
      (12, 'XXL - XXXL', '50', 'Italy'),
      (12, 'XXL - XXXL', '46', 'France'),
      (12, 'XXL - XXXL', '44', 'Denmark'),
      (12, 'XXL - XXXL', '52', 'Russia'),
      (12, 'XXL - XXXL', '44', 'Germany'),
      (12, 'XXL - XXXL', '18', 'Australia'),
      (12, 'XXL - XXXL', '17', 'Japan'),
      (13, 'XXS', '0', 'US'),
      (13, 'XXS', '4', 'UK'),
      (13, 'XXS', '36', 'Italy'),
      (13, 'XXS', '32', 'France'),
      (13, 'XXS', '30', 'Denmark'),
      (13, 'XXS', '38', 'Russia'),
      (13, 'XXS', '30', 'Germany'),
      (13, 'XXS', '4', 'Australia'),
      (13, 'XXS', '3', 'Japan'),
      (13, 'XXS - XS', '0', 'US'),
      (13, 'XXS - XS', '6', 'UK'),
      (13, 'XXS - XS', '38', 'Italy'),
      (13, 'XXS - XS', '34', 'France'),
      (13, 'XXS - XS', '32', 'Denmark'),
      (13, 'XXS - XS', '40', 'Russia'),
      (13, 'XXS - XS', '32', 'Germany'),
      (13, 'XXS - XS', '6', 'Australia'),
      (13, 'XXS - XS', '5', 'Japan'),
      (13, 'XS - S', '2 - 4', 'US'),
      (13, 'XS - S', '8', 'UK'),
      (13, 'XS - S', '40', 'Italy'),
      (13, 'XS - S', '36', 'France'),
      (13, 'XS - S', '34', 'Denmark'),
      (13, 'XS - S', '42', 'Russia'),
      (13, 'XS - S', '34', 'Germany'),
      (13, 'XS - S', '8', 'Australia'),
      (13, 'XS - S', '7', 'Japan'),
      (13, 'S - M', '4 - 6', 'US'),
      (13, 'S - M', '10', 'UK'),
      (13, 'S - M', '42', 'Italy'),
      (13, 'S - M', '38', 'France'),
      (13, 'S - M', '36', 'Denmark'),
      (13, 'S - M', '44', 'Russia'),
      (13, 'S - M', '36', 'Germany'),
      (13, 'S - M', '10', 'Australia'),
      (13, 'S - M', '9', 'Japan'),
      (13, 'M - L', '8', 'US'),
      (13, 'M - L', '12', 'UK'),
      (13, 'M - L', '44', 'Italy'),
      (13, 'M - L', '40', 'France'),
      (13, 'M - L', '38', 'Denmark'),
      (13, 'M - L', '46', 'Russia'),
      (13, 'M - L', '38', 'Germany'),
      (13, 'M - L', '12', 'Australia'),
      (13, 'M - L', '11', 'Japan'),
      (13, 'L - XL', '10', 'US'),
      (13, 'L - XL', '14', 'UK'),
      (13, 'L - XL', '46', 'Italy'),
      (13, 'L - XL', '42', 'France'),
      (13, 'L - XL', '40', 'Denmark'),
      (13, 'L - XL', '48', 'Russia'),
      (13, 'L - XL', '40', 'Germany'),
      (13, 'L - XL', '14', 'Australia'),
      (13, 'L - XL', '13', 'Japan'),
      (13, 'XL - XXL', '12', 'US'),
      (13, 'XL - XXL', '16', 'UK'),
      (13, 'XL - XXL', '48', 'Italy'),
      (13, 'XL - XXL', '44', 'France'),
      (13, 'XL - XXL', '42', 'Denmark'),
      (13, 'XL - XXL', '50', 'Russia'),
      (13, 'XL - XXL', '42', 'Germany'),
      (13, 'XL - XXL', '16', 'Australia'),
      (13, 'XL - XXL', '15', 'Japan'),
      (13, 'XXL - XXXL', '14', 'US'),
      (13, 'XXL - XXXL', '18', 'UK'),
      (13, 'XXL - XXXL', '50', 'Italy'),
      (13, 'XXL - XXXL', '46', 'France'),
      (13, 'XXL - XXXL', '44', 'Denmark'),
      (13, 'XXL - XXXL', '52', 'Russia'),
      (13, 'XXL - XXXL', '44', 'Germany'),
      (13, 'XXL - XXXL', '18', 'Australia'),
      (13, 'XXL - XXXL', '17', 'Japan'),
      (14, 'XXS', '0', 'US'),
      (14, 'XXS', '4', 'UK'),
      (14, 'XXS', '36', 'Italy'),
      (14, 'XXS', '32', 'France'),
      (14, 'XXS', '30', 'Denmark'),
      (14, 'XXS', '38', 'Russia'),
      (14, 'XXS', '30', 'Germany'),
      (14, 'XXS', '4', 'Australia'),
      (14, 'XXS', '3', 'Japan'),
      (14, 'XXS - XS', '0', 'US'),
      (14, 'XXS - XS', '6', 'UK'),
      (14, 'XXS - XS', '38', 'Italy'),
      (14, 'XXS - XS', '34', 'France'),
      (14, 'XXS - XS', '32', 'Denmark'),
      (14, 'XXS - XS', '40', 'Russia'),
      (14, 'XXS - XS', '32', 'Germany'),
      (14, 'XXS - XS', '6', 'Australia'),
      (14, 'XXS - XS', '5', 'Japan'),
      (14, 'XS - S', '2 - 4', 'US'),
      (14, 'XS - S', '8', 'UK'),
      (14, 'XS - S', '40', 'Italy'),
      (14, 'XS - S', '36', 'France'),
      (14, 'XS - S', '34', 'Denmark'),
      (14, 'XS - S', '42', 'Russia'),
      (14, 'XS - S', '34', 'Germany'),
      (14, 'XS - S', '8', 'Australia'),
      (14, 'XS - S', '7', 'Japan'),
      (14, 'S - M', '4 - 6', 'US'),
      (14, 'S - M', '10', 'UK'),
      (14, 'S - M', '42', 'Italy'),
      (14, 'S - M', '38', 'France'),
      (14, 'S - M', '36', 'Denmark'),
      (14, 'S - M', '44', 'Russia'),
      (14, 'S - M', '36', 'Germany'),
      (14, 'S - M', '10', 'Australia'),
      (14, 'S - M', '9', 'Japan'),
      (14, 'M - L', '8', 'US'),
      (14, 'M - L', '12', 'UK'),
      (14, 'M - L', '44', 'Italy'),
      (14, 'M - L', '40', 'France'),
      (14, 'M - L', '38', 'Denmark'),
      (14, 'M - L', '46', 'Russia'),
      (14, 'M - L', '38', 'Germany'),
      (14, 'M - L', '12', 'Australia'),
      (14, 'M - L', '11', 'Japan'),
      (14, 'L - XL', '10', 'US'),
      (14, 'L - XL', '14', 'UK'),
      (14, 'L - XL', '46', 'Italy'),
      (14, 'L - XL', '42', 'France'),
      (14, 'L - XL', '40', 'Denmark'),
      (14, 'L - XL', '48', 'Russia'),
      (14, 'L - XL', '40', 'Germany'),
      (14, 'L - XL', '14', 'Australia'),
      (14, 'L - XL', '13', 'Japan'),
      (14, 'XL - XXL', '12', 'US'),
      (14, 'XL - XXL', '16', 'UK'),
      (14, 'XL - XXL', '48', 'Italy'),
      (14, 'XL - XXL', '44', 'France'),
      (14, 'XL - XXL', '42', 'Denmark'),
      (14, 'XL - XXL', '50', 'Russia'),
      (14, 'XL - XXL', '42', 'Germany'),
      (14, 'XL - XXL', '16', 'Australia'),
      (14, 'XL - XXL', '15', 'Japan'),
      (14, 'XXL - XXXL', '14', 'US'),
      (14, 'XXL - XXXL', '18', 'UK'),
      (14, 'XXL - XXXL', '50', 'Italy'),
      (14, 'XXL - XXXL', '46', 'France'),
      (14, 'XXL - XXXL', '44', 'Denmark'),
      (14, 'XXL - XXXL', '52', 'Russia'),
      (14, 'XXL - XXXL', '44', 'Germany'),
      (14, 'XXL - XXXL', '18', 'Australia'),
      (14, 'XXL - XXXL', '17', 'Japan'),
      (5, 'XXS', '23', 'Any'),
      (5, 'XXS - XS', '24 - 25', 'Any'),
      (5, 'XS - S', '26 - 27', 'Any'),
      (5, 'S - M', '27 - 28', 'Any'),
      (5, 'M - L', '29 - 30', 'Any'),
      (5, 'L - XL', '31 - 32', 'Any'),
      (5, 'XL - XXL', '32 - 33', 'Any'),
      (20, 'XXS', '0', 'US'),
      (20, 'XXS', '4', 'UK'),
      (20, 'XXS', '36', 'Italy'),
      (20, 'XXS', '65', 'Europe'),
      (20, 'XXS - XS', '0', 'US'),
      (20, 'XXS - XS', '6', 'UK'),
      (20, 'XXS - XS', '38', 'Italy'),
      (20, 'XXS - XS', '70', 'Europe'),
      (20, 'XS - S', '2-4', 'US'),
      (20, 'XS - S', '8', 'UK'),
      (20, 'XS - S', '40', 'Italy'),
      (20, 'XS - S', '75', 'Europe'),
      (20, 'S - M', '4-6', 'US'),
      (20, 'S - M', '10', 'UK'),
      (20, 'S - M', '42', 'Italy'),
      (20, 'S - M', '80', 'Europe'),
      (20, 'M - L', '8', 'US'),
      (20, 'M - L', '12', 'UK'),
      (20, 'M - L', '44', 'Italy'),
      (20, 'M - L', '85', 'Europe'),
      (20, 'L - XL', '10', 'US'),
      (20, 'L - XL', '14', 'UK'),
      (20, 'L - XL', '46', 'Italy'),
      (20, 'L - XL', '90', 'Europe'),
      (20, 'XL - XXL', '12', 'US'),
      (20, 'XL - XXL', '16', 'UK'),
      (20, 'XL - XXL', '48', 'Italy'),
      (20, 'XL - XXL', '95', 'Europe'),
      (20, 'XXL - XXXL', '14', 'US'),
      (20, 'XXL - XXXL', '18', 'UK'),
      (20, 'XXL - XXXL', '50', 'Italy'),
      (20, 'XXL - XXXL', '100', 'Europe'),
      (16, 'US 4 (EU 34)', '4', 'US'),
      (16, 'US 4 (EU 34)', '34', 'Italy/Europe'),
      (16, 'US 4.5 (EU 34.5)', '4.5', 'US'),
      (16, 'US 4.5 (EU 34.5)', '34.5', 'Italy/Europe'),
      (16, 'US 5 (EU 35)', '5', 'US'),
      (16, 'US 5 (EU 35)', '35', 'Italy/Europe'),
      (16, 'US 5.5 (EU 35.5)', '5.5', 'US'),
      (16, 'US 5.5 (EU 35.5)', '35.5', 'Italy/Europe'),
      (16, 'US 6 (EU 36)', '6', 'US'),
      (16, 'US 6 (EU 36)', '36', 'Italy/Europe'),
      (16, 'US 6.5 (EU 36.5)', '6.5', 'US'),
      (16, 'US 6.5 (EU 36.5)', '36.5', 'Italy/Europe'),
      (16, 'US 7 (EU 37)', '7', 'US'),
      (16, 'US 7 (EU 37)', '37', 'Italy/Europe'),
      (16, 'US 7.5 (EU 37.5)', '7.5', 'US'),
      (16, 'US 7.5 (EU 37.5)', '37.5', 'Italy/Europe'),
      (16, 'US 8 (EU 38)', '8', 'US'),
      (16, 'US 8 (EU 38)', '38', 'Italy/Europe'),
      (16, 'US 8.5 (EU 38.5)', '8.5', 'US'),
      (16, 'US 8.5 (EU 38.5)', '38.5', 'Italy/Europe'),
      (16, 'US 9 (EU 39)', '9', 'US'),
      (16, 'US 9 (EU 39)', '39', 'Italy/Europe'),
      (16, 'US 9.5 (EU 39.5)', '9.5', 'US'),
      (16, 'US 9.5 (EU 39.5)', '39.5', 'Italy/Europe'),
      (16, 'US 10 (EU 40)', '10', 'US'),
      (16, 'US 10 (EU 40)', '40', 'Italy/Europe'),
      (16, 'US 10.5 (EU 40.5)', '10.5', 'US'),
      (16, 'US 10.5 (EU 40.5)', '40.5', 'Italy/Europe'),
      (16, 'US 11 (EU 41)', '11', 'US'),
      (16, 'US 11 (EU 41)', '41', 'Italy/Europe'),
      (16, 'US 11.5 (EU 41.5)', '11.5', 'US'),
      (16, 'US 11.5 (EU 41.5)', '41.5', 'Italy/Europe'),
      (16, 'US 12 (EU 42)', '12', 'US'),
      (16, 'US 12 (EU 42)', '42', 'Italy/Europe'),
      (29, 'XS', '44', 'Europe'),
      (29, 'XS', '44', 'Italy (IT)'),
      (29, 'XS', '34', 'UK/US CHEST'),
      (29, 'XS', '28', 'UK/US WAIST'),
      (29, 'XS', '28', 'France CHEST (FR)'),
      (29, 'XS', '36', 'France WAIST (FR)'),
      (29, 'S', '46', 'Europe'),
      (29, 'S', '46', 'Italy (IT)'),
      (29, 'S', '36', 'UK/US CHEST'),
      (29, 'S', '30', 'UK/US WAIST'),
      (29, 'S', '30', 'France CHEST (FR)'),
      (29, 'S', '38', 'France WAIST (FR)'),
      (29, 'M', '48', 'Europe'),
      (29, 'M', '48', 'Italy (IT)'),
      (29, 'M', '38', 'UK/US CHEST'),
      (29, 'M', '32', 'UK/US WAIST'),
      (29, 'M', '32', 'France CHEST (FR)'),
      (29, 'M', '40', 'France WAIST (FR)'),
      (29, 'L', '50', 'Europe'),
      (29, 'L', '50', 'Italy (IT)'),
      (29, 'L', '40', 'UK/US CHEST'),
      (29, 'L', '34', 'UK/US WAIST'),
      (29, 'L', '34', 'France CHEST (FR)'),
      (29, 'L', '42', 'France WAIST (FR)'),
      (29, 'XL', '52', 'Europe'),
      (29, 'XL', '52', 'Italy (IT)'),
      (29, 'XL', '42', 'UK/US CHEST'),
      (29, 'XL', '36', 'UK/US WAIST'),
      (29, 'XL', '36', 'France CHEST (FR)'),
      (29, 'XL', '44', 'France WAIST (FR)'),
      (29, 'XXL', '54', 'Europe'),
      (29, 'XXL', '54', 'Italy (IT)'),
      (29, 'XXL', '44', 'UK/US CHEST'),
      (29, 'XXL', '38', 'UK/US WAIST'),
      (29, 'XXL', '38', 'France CHEST (FR)'),
      (29, 'XXL', '46', 'France WAIST (FR)'),
      (21, 'XS', '37', 'European Collar (EU)'),
      (21, 'XS', '14.5', 'UK/US Collar'),
      (21, 'XS', '44', 'Italian (IT)'),
      (21, 'S', '38', 'European Collar (EU)'),
      (21, 'S', '15', 'UK/US Collar'),
      (21, 'S', '46', 'Italian (IT)'),
      (21, 'M', '39', 'European Collar (EU)'),
      (21, 'M', '15.5', 'UK/US Collar'),
      (21, 'M', '48', 'Italian (IT)'),
      (21, 'XL', '42', 'European Collar (EU)'),
      (21, 'XL', '16.5', 'UK/US Collar'),
      (21, 'XL', '52', 'Italian (IT)'),
      (21, 'XXL', '43', 'European Collar (EU)'),
      (21, 'XXL', '17', 'UK/US Collar'),
      (21, 'XXL', '54', 'Italian (IT)'),
      (25, 'XS', '44', 'Italian (IT)'),
      (25, 'XS', '28', 'UK/US Waist'),
      (25, 'XS', '36', 'French (FR)'),
      (25, 'S', '46', 'Italian (IT)'),
      (25, 'S', '30', 'UK/US Waist'),
      (25, 'S', '38', 'French (FR)'),
      (25, 'M', '48', 'Italian (IT)'),
      (25, 'M', '32', 'UK/US Waist'),
      (25, 'M', '40', 'French (FR)'),
      (25, 'L', '50', 'Italian (IT)'),
      (25, 'L', '34', 'UK/US Waist'),
      (25, 'L', '42', 'French (FR)'),
      (25, 'XL', '52', 'Italian (IT)'),
      (25, 'XL', '36', 'UK/US Waist'),
      (25, 'XL', '44', 'French (FR)'),
      (25, 'XXL', '54', 'Italian (IT)'),
      (25, 'XXL', '38', 'UK/US Waist'),
      (25, 'XXL', '46', 'French (FR)'),
      (26, 'XS', '44', 'Italian (IT)'),
      (26, 'XS', '28', 'UK/US Waist'),
      (26, 'XS', '36', 'French (FR)'),
      (26, 'S', '46', 'Italian (IT)'),
      (26, 'S', '30', 'UK/US Waist'),
      (26, 'S', '38', 'French (FR)'),
      (26, 'M', '48', 'Italian (IT)'),
      (26, 'M', '32', 'UK/US Waist'),
      (26, 'M', '40', 'French (FR)'),
      (26, 'L', '50', 'Italian (IT)'),
      (26, 'L', '34', 'UK/US Waist'),
      (26, 'L', '42', 'French (FR)'),
      (26, 'XL', '52', 'Italian (IT)'),
      (26, 'XL', '36', 'UK/US Waist'),
      (26, 'XL', '44', 'French (FR)'),
      (26, 'XXL', '54', 'Italian (IT)'),
      (26, 'XXL', '38', 'UK/US Waist'),
      (26, 'XXL', '46', 'French (FR)'),
      (27, 'XS', '44', 'Italian (IT)'),
      (27, 'XS', '28', 'UK/US Waist'),
      (27, 'XS', '36', 'French (FR)'),
      (27, 'S', '46', 'Italian (IT)'),
      (27, 'S', '30', 'UK/US Waist'),
      (27, 'S', '38', 'French (FR)'),
      (27, 'M', '48', 'Italian (IT)'),
      (27, 'M', '32', 'UK/US Waist'),
      (27, 'M', '40', 'French (FR)'),
      (27, 'L', '50', 'Italian (IT)'),
      (27, 'L', '34', 'UK/US Waist'),
      (27, 'L', '42', 'French (FR)'),
      (27, 'XL', '52', 'Italian (IT)'),
      (27, 'XL', '36', 'UK/US Waist'),
      (27, 'XL', '44', 'French (FR)'),
      (27, 'XXL', '54', 'Italian (IT)'),
      (27, 'XXL', '38', 'UK/US Waist'),
      (27, 'XXL', '46', 'French (FR)'),
      (28, 'XS', '44', 'Italian (IT)'),
      (28, 'XS', '28', 'UK/US Waist'),
      (28, 'XS', '36', 'French (FR)'),
      (28, 'S', '46', 'Italian (IT)'),
      (28, 'S', '30', 'UK/US Waist'),
      (28, 'S', '38', 'French (FR)'),
      (28, 'M', '48', 'Italian (IT)'),
      (28, 'M', '32', 'UK/US Waist'),
      (28, 'M', '40', 'French (FR)'),
      (28, 'L', '50', 'Italian (IT)'),
      (28, 'L', '34', 'UK/US Waist'),
      (28, 'L', '42', 'French (FR)'),
      (28, 'XL', '52', 'Italian (IT)'),
      (28, 'XL', '36', 'UK/US Waist'),
      (28, 'XL', '44', 'French (FR)'),
      (28, 'XXL', '54', 'Italian (IT)'),
      (28, 'XXL', '38', 'UK/US Waist'),
      (28, 'XXL', '46', 'French (FR)'),
      (30, 'XS', '44', 'Italian (IT)'),
      (30, 'XS', '28', 'UK/US Waist'),
      (30, 'XS', '36', 'French (FR)'),
      (30, 'S', '46', 'Italian (IT)'),
      (30, 'S', '30', 'UK/US Waist'),
      (30, 'S', '38', 'French (FR)'),
      (30, 'M', '48', 'Italian (IT)'),
      (30, 'M', '32', 'UK/US Waist'),
      (30, 'M', '40', 'French (FR)'),
      (30, 'L', '50', 'Italian (IT)'),
      (30, 'L', '34', 'UK/US Waist'),
      (30, 'L', '42', 'French (FR)'),
      (30, 'XL', '52', 'Italian (IT)'),
      (30, 'XL', '36', 'UK/US Waist'),
      (30, 'XL', '44', 'French (FR)'),
      (30, 'XXL', '54', 'Italian (IT)'),
      (30, 'XXL', '38', 'UK/US Waist'),
      (30, 'XXL', '46', 'French (FR)'),
      (37, 'XS', '85', 'European (EU)'),
      (37, 'XS', '28', 'UK/US Waist'),
      (37, 'S', '90', 'European (EU)'),
      (37, 'S', '30', 'UK/US Waist'),
      (37, 'M', '95', 'European (EU)'),
      (37, 'M', '32', 'UK/US Waist'),
      (37, 'L', '100', 'European (EU)'),
      (37, 'L', '34', 'UK/US Waist'),
      (37, 'XL', '105', 'European (EU)'),
      (37, 'XL', '36', 'UK/US Waist'),
      (37, 'XXL', '110', 'European (EU)'),
      (37, 'XXL', '38', 'UK/US Waist'),
      (32, 'US 6 (EU 39)', '39', 'EU'),
      (32, 'US 6 (EU 39)', '6', 'US'),
      (32, 'US 6.5 (EU 39.5)', '39.5', 'EU'),
      (32, 'US 6.5 (EU 39.5)', '6.5', 'US'),
      (32, 'US 7 (EU 40)', '40', 'EU'),
      (32, 'US 7 (EU 40)', '7', 'US'),
      (32, 'US 7.5 (EU 40.5)', '40.5', 'EU'),
      (32, 'US 7.5 (EU 40.5)', '7.5', 'US'),
      (32, 'US 8 (EU 41)', '41', 'EU'),
      (32, 'US 8 (EU 41)', '8', 'US'),
      (32, 'US 8.5 (EU 41.5)', '41.5', 'EU'),
      (32, 'US 8.5 (EU 41.5)', '8.5', 'US'),
      (32, 'US 9 (EU 42)', '42', 'EU'),
      (32, 'US 9 (EU 42)', '9', 'US'),
      (32, 'US 9.5 (EU 42.5)', '42.5', 'EU'),
      (32, 'US 9.5 (EU 42.5)', '9.5', 'US'),
      (32, 'US 10 (EU 43)', '43', 'EU'),
      (32, 'US 10 (EU 43)', '10', 'US'),
      (32, 'US 10.5 (EU 43.5)', '43.5', 'EU'),
      (32, 'US 10.5 (EU 43.5)', '10.5', 'US'),
      (32, 'US 11 (EU 44)', '44', 'EU'),
      (32, 'US 11 (EU 44)', '11', 'US'),
      (32, 'US 11.5 (EU 44.5)', '44.5', 'EU'),
      (32, 'US 11.5 (EU 44.5)', '11.5', 'US'),
      (32, 'US 12 (EU 45)', '45', 'EU'),
      (32, 'US 12 (EU 45)', '12', 'US'),
      (32, 'US 12.5 (EU 45.5)', '45.5', 'EU'),
      (32, 'US 12.5 (EU 45.5)', '12.5', 'US'),
      (32, 'US 13 (EU 46)', '46', 'EU'),
      (32, 'US 13 (EU 46)', '13', 'US'),
      (32, 'US 13.5 (EU 46.5)', '46.5', 'EU'),
      (32, 'US 13.5 (EU 46.5)', '13.5', 'US'),
      (32, 'US 14 (EU 47)', '47', 'EU'),
      (32, 'US 14 (EU 47)', '14', 'US');
    SQL
  end
end
