class AddNewImagingCategory < ActiveRecord::Migration
  def change
    execute <<-SQL
      INSERT INTO categories(id, name, icon, image, parent_id, imaging_category, level, unisex, created_at, updated_at) VALUES
      (50, 'Blazers & Sport coats', null, null, 41, null, 2, False, now(), now()),
      (51, 'Shirts', null, null, 41, null, 2, False, now(), now()),
      (52, 'Shoes', null, null, 41, null, 2, False, now(), now()),
      (53, 'Suits', null, null, 41, null, 2, False, now(), now()),
      (54, 'Sweaters', null, null, 41, null, 2, False, now(), now()),
      (55, 'Sweatshirts', null, null, 41, null, 2, False, now(), now()),
      (56, 'Swimwear', null, null, 41, null, 2, False, now(), now()),
      (57, 'Underwear', null, null, 41, null, 2, False, now(), now()),
      (58, 'Vests', null, null, 41, null, 2, False, now(), now()),
      (59, 'Accessories', null, null, 41, null, 2, False, now(), now()),
      (60, 'Hoodies', null, null, 41, null, 2, False, now(), now()),
      (61, 'Jeans', null, null, 41, null, 2, False, now(), now()),
      (62, 'Pants', null, null, 41, null, 2, False, now(), now()),
      (63, 'Shorts', null, null, 41, null, 2, False, now(), now()),
      (64, 'Sunglasses', null, null, 41, null, 2, False, now(), now()),
      (65, 'T-shirts', null, null, 41, null, 2, False, now(), now()),
      (66, 'Tank tops', null, null, 41, null, 2, False, now(), now()),
      (67, 'Accessories', null, null, 40, null, 2, False, now(), now()),
      (68, 'Hoodies', null, null, 40, null, 2, False, now(), now()),
      (69, 'Jeans', null, null, 40, null, 2, False, now(), now()),
      (70, 'Pants', null, null, 40, null, 2, False, now(), now()),
      (71, 'Shoes', null, null, 40, null, 2, False, now(), now()),
      (72, 'Shorts', null, null, 40, null, 2, False, now(), now()),
      (73, 'Sunglasses', null, null, 40, null, 2, False, now(), now()),
      (74, 'T-shirts', null, null, 40, null, 2, False, now(), now()),
      (75, 'Tank tops', null, null, 40, null, 2, False, now(), now()),
      (76, 'Blazers & Sport coats', null, null, 40, null, 2, False, now(), now()),
      (77, 'Dresses', null, null, 40, null, 2, False, now(), now()),
      (78, 'Ear rings', null, null, 40, null, 2, False, now(), now()),
      (79, 'Jumpsuits', null, null, 40, null, 2, False, now(), now()),
      (80, 'Leggings', null, null, 40, null, 2, False, now(), now()),
      (81, 'Shirts', null, null, 40, null, 2, False, now(), now()),
      (82, 'Shoulder bags', null, null, 40, null, 2, False, now(), now()),
      (83, 'Skirts', null, null, 40, null, 2, False, now(), now()),
      (84, 'Sweaters', null, null, 40, null, 2, False, now(), now()),
      (85, 'Sweatshirts', null, null, 40, null, 2, False, now(), now()),
      (86, 'Swimwear', null, null, 40, null, 2, False, now(), now()),
      (87, 'Underwear', null, null, 40, null, 2, False, now(), now()),
      (88, 'Vests', null, null, 40, null, 2, False, now(), now()),
      (89, 'Blazers & Sport coats', null, null, 50, 'man_blazers_sport_coats', 3, FALSE, now(), now()),
      (90, 'Polo shirts', null, null, 51, 'man_polo_shirt', 3, FALSE, now(), now()),
      (91, 'Shirt buttons', null, null, 51, 'man_shirt_button', 3, FALSE, now(), now()),
      (92, 'Boots', null, null, 52, 'shoe_man_boots', 3, FALSE, now(), now()),
      (93, 'Loafers', null, null, 52, 'shoe_loafers', 3, FALSE, now(), now()),
      (94, 'Oxfords', null, null, 52, 'shoe_oxfords', 3, FALSE, now(), now()),
      (95, 'Suits', null, null, 53, 'man_suit', 3, FALSE, now(), now()),
      (96, 'Sweaters', null, null, 54, 'man_sweater', 3, FALSE, now(), now()),
      (97, 'Sweatshirts', null, null, 55, 'sweatshirt_man', 3, FALSE, now(), now()),
      (98, 'Swimwear', null, null, 56, 'man_swimwear', 3, FALSE, now(), now()),
      (99, 'Underwear', null, null, 57, 'man_underwear', 3, FALSE, now(), now()),
      (100, 'Vests', null, null, 58, 'man_vest', 3, FALSE, now(), now()),
      (101, 'Baseball caps', null, null, 59, 'baseball_caps', 3, TRUE, now(), now()),
      (102, 'Belts', null, null, 59, 'belt', 3, TRUE, now(), now()),
      (103, 'Bracelets', null, null, 59, 'bracelet', 3, TRUE, now(), now()),
      (104, 'Hats', null, null, 59, 'hats', 3, TRUE, now(), now()),
      (105, 'Messengers', null, null, 59, 'messenger', 3, TRUE, now(), now()),
      (106, 'Necklaces', null, null, 59, 'neckless', 3, TRUE, now(), now()),
      (107, 'Smartwatches', null, null, 59, 'smartwatch', 3, TRUE, now(), now()),
      (108, 'Socks', null, null, 59, 'socks', 3, TRUE, now(), now()),
      (109, 'Wallets', null, null, 59, 'wallet', 3, TRUE, now(), now()),
      (110, 'Watches', null, null, 59, 'watch', 3, TRUE, now(), now()),
      (111, 'Hoodies', null, null, 60, 'hoodie', 3, TRUE, now(), now()),
      (112, 'Jeans', null, null, 61, 'jeans', 3, TRUE, now(), now()),
      (113, 'Pants', null, null, 62, 'pants', 3, TRUE, now(), now()),
      (114, 'Flip flops', null, null, 52, 'shoe_flip_flops', 3, TRUE, now(), now()),
      (115, 'High tops', null, null, 52, 'shoe_high_tops', 3, TRUE, now(), now()),
      (116, 'Sandals', null, null, 52, 'shoe_sandals', 3, TRUE, now(), now()),
      (117, 'Slippers', null, null, 52, 'shoe_slippers', 3, TRUE, now(), now()),
      (118, 'Sneaker runnings', null, null, 52, 'shoe_sneakers_running', 3, TRUE, now(), now()),
      (119, 'Shorts', null, null, 63, 'shorts', 3, TRUE, now(), now()),
      (120, 'Sunglasses', null, null, 64, 'sunglasses', 3, TRUE, now(), now()),
      (121, 'T-shirts', null, null, 65, 't_shirt', 3, TRUE, now(), now()),
      (122, 'Tank tops', null, null, 66, 'tank_top', 3, TRUE, now(), now()),
      (123, 'Baseball caps', null, null, 67, 'baseball_caps', 3, TRUE, now(), now()),
      (124, 'Belts', null, null, 67, 'belt', 3, TRUE, now(), now()),
      (125, 'Bracelets', null, null, 67, 'bracelet', 3, TRUE, now(), now()),
      (126, 'Hats', null, null, 67, 'hats', 3, TRUE, now(), now()),
      (127, 'Messengers', null, null, 67, 'messenger', 3, TRUE, now(), now()),
      (128, 'Necklaces', null, null, 67, 'neckless', 3, TRUE, now(), now()),
      (129, 'Smartwatches', null, null, 67, 'smartwatch', 3, TRUE, now(), now()),
      (130, 'Socks', null, null, 67, 'socks', 3, TRUE, now(), now()),
      (131, 'Wallets', null, null, 67, 'wallet', 3, TRUE, now(), now()),
      (132, 'Watches', null, null, 67, 'watch', 3, TRUE, now(), now()),
      (133, 'Hoodies', null, null, 68, 'hoodie', 3, TRUE, now(), now()),
      (134, 'Jeans', null, null, 69, 'jeans', 3, TRUE, now(), now()),
      (135, 'Pants', null, null, 70, 'pants', 3, TRUE, now(), now()),
      (136, 'Flip flops', null, null, 71, 'shoe_flip_flops', 3, TRUE, now(), now()),
      (137, 'High tops', null, null, 71, 'shoe_high_tops', 3, TRUE, now(), now()),
      (138, 'Sandals', null, null, 71, 'shoe_sandals', 3, TRUE, now(), now()),
      (139, 'Slippers', null, null, 71, 'shoe_slippers', 3, TRUE, now(), now()),
      (140, 'Sneaker runnings', null, null, 71, 'shoe_sneakers_running', 3, TRUE, now(), now()),
      (141, 'Shorts', null, null, 72, 'shorts', 3, TRUE, now(), now()),
      (142, 'Sunglasses', null, null, 73, 'sunglasses', 3, TRUE, now(), now()),
      (143, 'T-shirts', null, null, 74, 't_shirt', 3, TRUE, now(), now()),
      (144, 'Tank tops', null, null, 75, 'tank_top', 3, TRUE, now(), now()),
      (145, 'Blazers & Sport coats', null, null, 76, 'woman_blazer_sport_coats', 3, FALSE, now(), now()),
      (146, 'Casual', null, null, 77, 'woman_dress_casual', 3, FALSE, now(), now()),
      (147, 'Club', null, null, 77, 'woman_dress_club', 3, FALSE, now(), now()),
      (148, 'Formal', null, null, 77, 'woman_dress_formal', 3, FALSE, now(), now()),
      (149, 'Ear rings', null, null, 78, 'ear_rings', 3, FALSE, now(), now()),
      (150, 'Jumpsuits', null, null, 79, 'woman_jumpsuit', 3, FALSE, now(), now()),
      (151, 'Leggings', null, null, 80, 'leggin', 3, FALSE, now(), now()),
      (152, 'Polo shirts', null, null, 81, 'woman_polo', 3, FALSE, now(), now()),
      (153, 'Boots', null, null, 71, 'shoe_woman_boots', 3, FALSE, now(), now()),
      (154, 'Flats', null, null, 71, 'shoe_flats', 3, FALSE, now(), now()),
      (155, 'Pumps', null, null, 71, 'shoe_pumps', 3, FALSE, now(), now()),
      (156, 'Shoulder bags', null, null, 82, 'woman_shoulder_bag', 3, FALSE, now(), now()),
      (157, 'Skirts', null, null, 83, 'skirt', 3, FALSE, now(), now()),
      (158, 'Sweaters', null, null, 84, 'woman_sweater', 3, FALSE, now(), now()),
      (159, 'Sweatshirts', null, null, 85, 'sweatshirt_woman', 3, FALSE, now(), now()),
      (160, 'Swimwear', null, null, 86, 'woman_swimwear', 3, FALSE, now(), now()),
      (161, 'Underwear', null, null, 87, 'woman_underwaer', 3, FALSE, now(), now()),
      (162, 'Vests', null, null, 88, 'woman_vest', 3, FALSE, now(), now());
    SQL
  end
end
